# Generated by Django 5.2.17 on 2026-09-18 20:27

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_to_image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextToImageModelPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(default='grok-imagine', max_length=100, verbose_name='النموذج / Model')),
                ('provider_name', models.CharField(default='CrunAI', max_length=100, verbose_name='المزود / Provider')),
                ('cost_per_image', models.DecimalField(decimal_places=4, default=Decimal('2.0000'), max_digits=10, verbose_name='تكلفة الصورة / Cost Per Image')),
                ('allowed_wallet', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('both', 'Both')], default='both', max_length=20, verbose_name='المحفظة / Allowed Wallet')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل / Is Active')),
            ],
            options={
                'verbose_name': 'تسعير توليد الصور / T2I Pricing',
                'verbose_name_plural': 'أسعار توليد الصور / T2I Pricings',
            },
        ),
        migrations.CreateModel(
            name='TextToImageSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='تفعيل الأداة / Is Active')),
                ('is_maintenance_mode', models.BooleanField(default=False, verbose_name='وضع الصيانة / Maintenance Mode')),
                ('is_coming_soon', models.BooleanField(default=False, verbose_name='قريباً / Coming Soon')),
                ('max_prompt_length', models.IntegerField(default=2000, verbose_name='أقصى طول للوصف / Max Prompt Length')),
                ('max_concurrent_operations', models.IntegerField(default=10, verbose_name='أقصى عمليات متزامنة / Max Concurrency')),
                ('allowed_wallet', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('both', 'Both')], default='both', max_length=20, verbose_name='المحفظة / Allowed Wallet')),
            ],
            options={
                'verbose_name': 'إعدادات توليد الصور / T2I Setting',
                'verbose_name_plural': 'إعدادات توليد الصور / T2I Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='texttoimagegeneration',
            options={'verbose_name': 'سجل توليد صورة من نص / T2I Record', 'verbose_name_plural': 'سجلات توليد الصور من نص / T2I Records'},
        ),
    ]
