# Generated by Django 5.2.17 on 2026-09-18 19:31

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TtsGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('voice_name', models.CharField(max_length=100)),
                ('language', models.CharField(default='ar', max_length=50)),
                ('style_instruction', models.CharField(blank=True, default='', max_length=255)),
                ('quality', models.CharField(default='Standard', max_length=20)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('result_url', models.CharField(blank=True, default='', max_length=500)),
                ('standard_credits_used', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('premium_credits_used', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('error_message', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tts_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
