# Generated by Django 5.2.17 on 2026-09-18 20:27

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TtsModelPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quality_level', models.CharField(default='standard', max_length=50, verbose_name='مستوى الجودة / Quality')),
                ('model_name', models.CharField(default='gemini-2.5-flash-preview-tts', max_length=100, verbose_name='اسم النموذج / Model')),
                ('provider_name', models.CharField(default='Gemini', max_length=100, verbose_name='المزود / Provider')),
                ('billing_type', models.CharField(choices=[('per_request', 'Per Request'), ('per_char', 'Per Character')], default='per_request', max_length=50, verbose_name='نوع الفوترة / Billing Type')),
                ('fixed_cost', models.DecimalField(decimal_places=4, default=Decimal('0.1000'), max_digits=10, verbose_name='التكلفة الثابتة / Fixed Cost')),
                ('cost_per_char', models.DecimalField(decimal_places=4, default=Decimal('0.0001'), max_digits=10, verbose_name='تكلفة الحرف / Cost Per Char')),
                ('allowed_wallet', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('both', 'Both')], default='both', max_length=20, verbose_name='المحفظة / Allowed Wallet')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل / Is Active')),
            ],
            options={
                'verbose_name': 'تسعير تحويل النص إلى صوت / TTS Pricing',
                'verbose_name_plural': 'أسعار تحويل النص إلى صوت / TTS Pricings',
            },
        ),
        migrations.CreateModel(
            name='TtsSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='تفعيل الأداة / Is Active')),
                ('is_maintenance_mode', models.BooleanField(default=False, verbose_name='وضع الصيانة / Maintenance Mode')),
                ('is_coming_soon', models.BooleanField(default=False, verbose_name='قريباً / Coming Soon')),
                ('max_text_length', models.IntegerField(default=5000, verbose_name='الحد الأقصى للحروف / Max Text Length')),
                ('max_concurrent_operations', models.IntegerField(default=10, verbose_name='أقصى عمليات متزامنة / Max Concurrency')),
                ('allowed_wallet', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('both', 'Both (Standard First)')], default='both', max_length=20, verbose_name='المحفظة المسموحة / Allowed Wallet')),
            ],
            options={
                'verbose_name': 'إعدادات تحويل النص إلى صوت / TTS Setting',
                'verbose_name_plural': 'إعدادات تحويل النص إلى صوت / TTS Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='ttsgeneration',
            options={'verbose_name': 'سجل توليد صوتي / TTS Record', 'verbose_name_plural': 'سجلات التوليد الصوتي / TTS Records'},
        ),
    ]
