# Generated by Django 5.2.17 on 2026-09-18 20:27

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SttModelPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(default='whisper-large-v3', max_length=100, verbose_name='النموذج / Model')),
                ('provider_name', models.CharField(default='Whisper', max_length=100, verbose_name='المزود / Provider')),
                ('billing_type', models.CharField(choices=[('per_request', 'Per Request'), ('per_minute', 'Per Minute')], default='per_request', max_length=50, verbose_name='نوع الفوترة / Billing Type')),
                ('fixed_cost', models.DecimalField(decimal_places=4, default=Decimal('0.5000'), max_digits=10, verbose_name='التكلفة الثابتة / Fixed Cost')),
                ('cost_per_minute', models.DecimalField(decimal_places=4, default=Decimal('0.2000'), max_digits=10, verbose_name='تكلفة الدقيقة / Cost Per Minute')),
                ('allowed_wallet', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('both', 'Both')], default='both', max_length=20, verbose_name='المحفظة / Allowed Wallet')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل / Is Active')),
            ],
            options={
                'verbose_name': 'تسعير تحويل الصوت إلى نص / STT Pricing',
                'verbose_name_plural': 'أسعار تحويل الصوت إلى نص / STT Pricings',
            },
        ),
        migrations.CreateModel(
            name='SttSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='تفعيل الأداة / Is Active')),
                ('is_maintenance_mode', models.BooleanField(default=False, verbose_name='وضع الصيانة / Maintenance Mode')),
                ('is_coming_soon', models.BooleanField(default=False, verbose_name='قريباً / Coming Soon')),
                ('max_audio_size_mb', models.IntegerField(default=25, verbose_name='أقصى حجم للملف بالميجابايت / Max Size MB')),
                ('max_duration_seconds', models.IntegerField(default=300, verbose_name='أقصى مدة بالثواني / Max Duration Sec')),
                ('max_concurrent_operations', models.IntegerField(default=10, verbose_name='أقصى عمليات متزامنة / Max Concurrency')),
                ('allowed_wallet', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('both', 'Both')], default='both', max_length=20, verbose_name='المحفظة / Allowed Wallet')),
            ],
            options={
                'verbose_name': 'إعدادات تحويل الصوت إلى نص / STT Setting',
                'verbose_name_plural': 'إعدادات تحويل الصوت إلى نص / STT Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='stttranscription',
            options={'verbose_name': 'سجل تفريغ صوتي / STT Record', 'verbose_name_plural': 'سجلات التفريغ الصوتي / STT Records'},
        ),
    ]
