# Generated by Django 5.2.17 on 2026-09-18 20:27

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_to_video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceToVideoModelPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(default='bytedance/seedance2-0-mini-r2v', max_length=100, verbose_name='النموذج / Model')),
                ('provider_name', models.CharField(default='CrunAI', max_length=100, verbose_name='المزود / Provider')),
                ('billing_type', models.CharField(choices=[('per_request', 'Per Request'), ('per_second', 'Per Second')], default='per_second', max_length=50, verbose_name='نوع الفوترة / Billing Type')),
                ('cost_per_second_720p', models.DecimalField(decimal_places=4, default=Decimal('0.0286'), max_digits=10, verbose_name='تكلفة الثانية 720p / Per Sec 720p')),
                ('cost_per_second_1080p', models.DecimalField(decimal_places=4, default=Decimal('0.0286'), max_digits=10, verbose_name='تكلفة الثانية 1080p / Per Sec 1080p')),
                ('fixed_cost', models.DecimalField(decimal_places=4, default=Decimal('15.0000'), max_digits=10, verbose_name='التكلفة الثابتة / Fixed Cost')),
                ('allowed_wallet', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('both', 'Both')], default='both', max_length=20, verbose_name='المحفظة / Allowed Wallet')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل / Is Active')),
            ],
            options={
                'verbose_name': 'تسعير تحويل المرجع إلى فيديو / R2V Pricing',
                'verbose_name_plural': 'أسعار تحويل المرجع إلى فيديو / R2V Pricings',
            },
        ),
        migrations.CreateModel(
            name='ReferenceToVideoSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='تفعيل الأداة / Is Active')),
                ('is_maintenance_mode', models.BooleanField(default=False, verbose_name='وضع الصيانة / Maintenance Mode')),
                ('is_coming_soon', models.BooleanField(default=False, verbose_name='قريباً / Coming Soon')),
                ('max_prompt_length', models.IntegerField(default=1000, verbose_name='أقصى طول للوصف / Max Prompt Length')),
                ('max_duration_seconds', models.IntegerField(default=30, verbose_name='أقصى مدة بالثواني / Max Duration Sec')),
                ('max_concurrent_operations', models.IntegerField(default=10, verbose_name='أقصى عمليات متزامنة / Max Concurrency')),
                ('allowed_wallet', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('both', 'Both')], default='both', max_length=20, verbose_name='المحفظة / Allowed Wallet')),
            ],
            options={
                'verbose_name': 'إعدادات تحويل المرجع إلى فيديو / R2V Setting',
                'verbose_name_plural': 'إعدادات تحويل المرجع إلى فيديو / R2V Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='referencetovideogeneration',
            options={'verbose_name': 'سجل تحويل مرجع إلى فيديو / R2V Record', 'verbose_name_plural': 'سجلات تحويل مرجع إلى فيديو / R2V Records'},
        ),
    ]
