# Generated by Django 5.2.17 on 2026-09-18 19:31

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualPaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('account_details', models.TextField(help_text='Account number, IBAN, Vodafone Cash number, etc.')),
                ('instructions', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('description_ar', models.TextField(blank=True, default='')),
                ('price_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('price_egp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('duration_days', models.IntegerField(default=30)),
                ('grace_period_days', models.IntegerField(default=3)),
                ('standard_credits_grant', models.DecimalField(decimal_places=4, default=Decimal('100.0000'), max_digits=14)),
                ('premium_credits_grant', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('is_free_trial', models.BooleanField(default=False)),
                ('is_default_registration_plan', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('tts_enabled', models.BooleanField(default=True)),
                ('stt_enabled', models.BooleanField(default=True)),
                ('text_to_video_enabled', models.BooleanField(default=True)),
                ('image_to_video_enabled', models.BooleanField(default=True)),
                ('reference_to_video_enabled', models.BooleanField(default=True)),
                ('lipsync_enabled', models.BooleanField(default=True)),
                ('motion_control_enabled', models.BooleanField(default=True)),
                ('text_to_image_enabled', models.BooleanField(default=True)),
                ('avatar_video_enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('method', models.CharField(choices=[('paymob', 'Paymob (EGP)'), ('paypal', 'PayPal (USD)'), ('manual', 'Manual Bank/Wallet')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('receipt_url', models.CharField(blank=True, max_length=500, null=True)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.plan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('freeze', 'Freeze'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='active', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tool_name', models.CharField(blank=True, default='', max_length=50)),
                ('wallet_type', models.CharField(choices=[('standard', 'Standard Credits'), ('premium', 'Premium Credits')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=4, max_digits=14)),
                ('description', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
