# Generated by Django 5.2.17 on 2026-09-18 20:27

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipsync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LipSyncModelPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(default='vidu-lipsync-std', max_length=100, verbose_name='النموذج / Model')),
                ('provider_name', models.CharField(default='CrunAI', max_length=100, verbose_name='المزود / Provider')),
                ('billing_type', models.CharField(choices=[('flat_rate', 'Flat Rate'), ('per_second', 'Per Second')], default='flat_rate', max_length=50, verbose_name='نوع الفوترة / Billing Type')),
                ('cost_per_generation', models.DecimalField(decimal_places=4, default=Decimal('10.0000'), max_digits=10, verbose_name='التكلفة الثابتة / Cost Per Gen')),
                ('cost_per_second', models.DecimalField(decimal_places=4, default=Decimal('0.5000'), max_digits=10, verbose_name='تكلفة الثانية / Per Sec')),
                ('allowed_wallet', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('both', 'Both')], default='both', max_length=20, verbose_name='المحفظة / Allowed Wallet')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل / Is Active')),
            ],
            options={
                'verbose_name': 'تسعير مزامنة الشفاه / LipSync Pricing',
                'verbose_name_plural': 'أسعار مزامنة الشفاه / LipSync Pricings',
            },
        ),
        migrations.CreateModel(
            name='LipSyncSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='تفعيل الأداة / Is Active')),
                ('is_maintenance_mode', models.BooleanField(default=False, verbose_name='وضع الصيانة / Maintenance Mode')),
                ('is_coming_soon', models.BooleanField(default=False, verbose_name='قريباً / Coming Soon')),
                ('max_video_size_mb', models.IntegerField(default=100, verbose_name='أقصى حجم فيديو MB / Max Video MB')),
                ('max_audio_size_mb', models.IntegerField(default=25, verbose_name='أقصى حجم صوت MB / Max Audio MB')),
                ('max_duration_seconds', models.IntegerField(default=120, verbose_name='أقصى مدة بالثواني / Max Duration Sec')),
                ('max_concurrent_operations', models.IntegerField(default=10, verbose_name='أقصى عمليات متزامنة / Max Concurrency')),
                ('allowed_wallet', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('both', 'Both')], default='both', max_length=20, verbose_name='المحفظة / Allowed Wallet')),
            ],
            options={
                'verbose_name': 'إعدادات مزامنة الشفاه / LipSync Setting',
                'verbose_name_plural': 'إعدادات مزامنة الشفاه / LipSync Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='lipsyncgeneration',
            options={'verbose_name': 'سجل مزامنة الشفاه / LipSync Record', 'verbose_name_plural': 'سجلات مزامنة الشفاه / LipSync Records'},
        ),
    ]
