# Generated by Django 5.2.17 on 2026-09-18 19:31

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextToVideoGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.TextField()),
                ('model_name', models.CharField(default='veo-3.1-fast', max_length=50)),
                ('resolution', models.CharField(default='720p', max_length=20)),
                ('duration_seconds', models.IntegerField(default=5)),
                ('aspect_ratio', models.CharField(default='16:9', max_length=20)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('result_url', models.CharField(blank=True, default='', max_length=500)),
                ('standard_credits_used', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('premium_credits_used', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('error_message', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_to_video_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
