# Generated by Django 5.2.17 on 2026-09-18 20:27

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_to_video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextToVideoModelPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(default='veo 3.1 Fast', max_length=100, verbose_name='النموذج / Model')),
                ('provider_name', models.CharField(default='CrunAI', max_length=100, verbose_name='المزود / Provider')),
                ('billing_type', models.CharField(choices=[('per_request', 'Per Request'), ('per_second', 'Per Second')], default='per_request', max_length=50, verbose_name='نوع الفوترة / Billing Type')),
                ('fixed_cost_720p', models.DecimalField(decimal_places=4, default=Decimal('30.0000'), max_digits=10, verbose_name='تكلفة 720p / Cost 720p')),
                ('fixed_cost_1080p', models.DecimalField(decimal_places=4, default=Decimal('37.5000'), max_digits=10, verbose_name='تكلفة 1080p / Cost 1080p')),
                ('fixed_cost_4k', models.DecimalField(decimal_places=4, default=Decimal('90.0000'), max_digits=10, verbose_name='تكلفة 4K / Cost 4K')),
                ('cost_per_second_720p', models.DecimalField(decimal_places=4, default=Decimal('4.5000'), max_digits=10, verbose_name='تكلفة الثانية 720p / Per Sec 720p')),
                ('cost_per_second_1080p', models.DecimalField(decimal_places=4, default=Decimal('8.0000'), max_digits=10, verbose_name='تكلفة الثانية 1080p / Per Sec 1080p')),
                ('allowed_wallet', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('both', 'Both')], default='both', max_length=20, verbose_name='المحفظة / Allowed Wallet')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل / Is Active')),
            ],
            options={
                'verbose_name': 'تسعير تحويل النص إلى فيديو / T2V Pricing',
                'verbose_name_plural': 'أسعار تحويل النص إلى فيديو / T2V Pricings',
            },
        ),
        migrations.CreateModel(
            name='TextToVideoSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='تفعيل الأداة / Is Active')),
                ('is_maintenance_mode', models.BooleanField(default=False, verbose_name='وضع الصيانة / Maintenance Mode')),
                ('is_coming_soon', models.BooleanField(default=False, verbose_name='قريباً / Coming Soon')),
                ('max_prompt_length', models.IntegerField(default=1000, verbose_name='أقصى طول للوصف / Max Prompt Length')),
                ('max_duration_seconds', models.IntegerField(default=30, verbose_name='أقصى مدة بالثواني / Max Duration Sec')),
                ('default_resolution', models.CharField(default='720p', max_length=20, verbose_name='الدقة الافتراضية / Default Res')),
                ('max_concurrent_operations', models.IntegerField(default=10, verbose_name='أقصى عمليات متزامنة / Max Concurrency')),
                ('allowed_wallet', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('both', 'Both')], default='both', max_length=20, verbose_name='المحفظة / Allowed Wallet')),
            ],
            options={
                'verbose_name': 'إعدادات تحويل النص إلى فيديو / T2V Setting',
                'verbose_name_plural': 'إعدادات تحويل النص إلى فيديو / T2V Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='texttovideogeneration',
            options={'verbose_name': 'سجل توليد فيديو من نص / T2V Record', 'verbose_name_plural': 'سجلات توليد الفيديو من نص / T2V Records'},
        ),
    ]
