# Generated by Django 5.2.17 on 2026-09-18 20:27

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotionControlModelPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(default='kling-motion-control', max_length=100, verbose_name='النموذج / Model')),
                ('provider_name', models.CharField(default='KlingAI', max_length=100, verbose_name='المزود / Provider')),
                ('billing_type', models.CharField(choices=[('flat_rate', 'Flat Rate'), ('per_second', 'Per Second')], default='flat_rate', max_length=50, verbose_name='نوع الفوترة / Billing Type')),
                ('cost_per_generation', models.DecimalField(decimal_places=4, default=Decimal('20.0000'), max_digits=10, verbose_name='التكلفة الثابتة / Cost Per Gen')),
                ('cost_per_second', models.DecimalField(decimal_places=4, default=Decimal('2.0000'), max_digits=10, verbose_name='تكلفة الثانية / Per Sec')),
                ('allowed_wallet', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('both', 'Both')], default='both', max_length=20, verbose_name='المحفظة / Allowed Wallet')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل / Is Active')),
            ],
            options={
                'verbose_name': 'تسعير التحكم بالحركة / Motion Pricing',
                'verbose_name_plural': 'أسعار التحكم بالحركة / Motion Pricings',
            },
        ),
        migrations.CreateModel(
            name='MotionControlSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='تفعيل الأداة / Is Active')),
                ('is_maintenance_mode', models.BooleanField(default=False, verbose_name='وضع الصيانة / Maintenance Mode')),
                ('is_coming_soon', models.BooleanField(default=False, verbose_name='قريباً / Coming Soon')),
                ('max_video_size_mb', models.IntegerField(default=100, verbose_name='أقصى حجم فيديو MB / Max Video MB')),
                ('max_image_size_mb', models.IntegerField(default=25, verbose_name='أقصى حجم صورة MB / Max Image MB')),
                ('max_duration_seconds', models.IntegerField(default=30, verbose_name='أقصى مدة بالثواني / Max Duration Sec')),
                ('max_concurrent_operations', models.IntegerField(default=10, verbose_name='أقصى عمليات متزامنة / Max Concurrency')),
                ('allowed_wallet', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('both', 'Both')], default='both', max_length=20, verbose_name='المحفظة / Allowed Wallet')),
            ],
            options={
                'verbose_name': 'إعدادات التحكم بالحركة / Motion Setting',
                'verbose_name_plural': 'إعدادات التحكم بالحركة / Motion Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='motioncontrolgeneration',
            options={'verbose_name': 'سجل التحكم بالحركة / Motion Record', 'verbose_name_plural': 'سجلات التحكم بالحركة / Motion Records'},
        ),
    ]
