# Generated by Django 5.2.17 on 2026-09-18 20:27

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar_video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarVideoModelPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(default='kling-avatar', max_length=100, verbose_name='النموذج / Model')),
                ('provider_name', models.CharField(default='KlingAI', max_length=100, verbose_name='المزود / Provider')),
                ('cost_per_generation', models.DecimalField(decimal_places=4, default=Decimal('15.0000'), max_digits=10, verbose_name='التكلفة الثابتة / Cost Per Gen')),
                ('cost_per_second', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=10, verbose_name='تكلفة الثانية / Per Sec')),
                ('allowed_wallet', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('both', 'Both')], default='both', max_length=20, verbose_name='المحفظة / Allowed Wallet')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل / Is Active')),
            ],
            options={
                'verbose_name': 'تسعير الأفاتار المتكلم / Avatar Pricing',
                'verbose_name_plural': 'أسعار الأفاتار المتكلم / Avatar Pricings',
            },
        ),
        migrations.CreateModel(
            name='AvatarVideoSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='تفعيل الأداة / Is Active')),
                ('is_maintenance_mode', models.BooleanField(default=False, verbose_name='وضع الصيانة / Maintenance Mode')),
                ('is_coming_soon', models.BooleanField(default=False, verbose_name='قريباً / Coming Soon')),
                ('max_text_length', models.IntegerField(default=2000, verbose_name='أقصى طول للنص / Max Text Length')),
                ('max_duration_seconds', models.IntegerField(default=60, verbose_name='أقصى مدة بالثواني / Max Duration Sec')),
                ('max_concurrent_operations', models.IntegerField(default=10, verbose_name='أقصى عمليات متزامنة / Max Concurrency')),
                ('allowed_wallet', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('both', 'Both')], default='both', max_length=20, verbose_name='المحفظة / Allowed Wallet')),
            ],
            options={
                'verbose_name': 'إعدادات الأفاتار المتكلم / Avatar Setting',
                'verbose_name_plural': 'إعدادات الأفاتار المتكلم / Avatar Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='avatarvideogeneration',
            options={'verbose_name': 'سجل فيديو الأفاتار / Avatar Record', 'verbose_name_plural': 'سجلات فيديو الأفاتار / Avatar Records'},
        ),
    ]
